#!/bin/bash

set -ex


# jupyter nbextension enable python-markdown/main
# jupyter nbextension enable --py widgetsnbextension

# Notebooks w/ scripts that auto-run code must be "trusted" to work the first time
jupyter trust *.ipynb

# for start config
# exec "$@"