#!/bin/bash

set -ex


jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Notebooks w/ scripts that auto-run code must be "trusted" to work the first time
jupyter trust mvp_kaniko.ipynb

jupyter trust bilibo.ipynb



# exec "$@"